// Code generated by "stringer -type=SynchronizerState"; DO NOT EDIT.

package jthreadparser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LockedState-0]
	_ = x[ParkingToWaitForState-1]
	_ = x[WaitingOnState-2]
	_ = x[WaitingToLockState-3]
}

const _SynchronizerState_name = "LockedStateParkingToWaitForStateWaitingOnStateWaitingToLockState"

var _SynchronizerState_index = [...]uint8{0, 11, 32, 46, 64}

func (i SynchronizerState) String() string {
	if i < 0 || i >= SynchronizerState(len(_SynchronizerState_index)-1) {
		return "SynchronizerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SynchronizerState_name[_SynchronizerState_index[i]:_SynchronizerState_index[i+1]]
}
